// Strengths & Weaknesses are INTERNAL - derived from choices the founder made
// in the Project Submission form (business model, budget, how complete the
// submission is).
// Opportunities & Threats are EXTERNAL - derived from the real market and
// competitor data already fetched for the selected industry.
//
// Every item below traces back to a specific, checkable rule - the same
// philosophy as riskEngine.js and forecast.js. Nothing here is generated by
// a model; it's all deterministic logic over data already in the app.

import { parseBudgetToCr } from './riskEngine.js'

const LOW_COMPLEXITY_MODELS = ['SaaS', 'Subscription', 'Services']
const HIGH_COMPLEXITY_MODELS = ['Hardware', 'Marketplace']

function buildStrengths(form) {
  const items = []
  const budgetCr = parseBudgetToCr(form?.budget)

  if (LOW_COMPLEXITY_MODELS.includes(form?.businessModel)) {
    items.push({
      text: `${form.businessModel} is a mature, well-understood delivery model in the Indian market`,
      basis: `Business Model: ${form.businessModel}`,
    })
  }
  if (budgetCr != null && budgetCr * 100 >= 100) {
    items.push({
      text: `A budget of ${form.budget} gives a comfortable runway for early-stage validation`,
      basis: `Budget: ${form.budget}`,
    })
  }
  if (form?.targetMarket && form.targetMarket.trim().length > 0) {
    items.push({
      text: `A clearly defined target market ("${form.targetMarket}") sharpens go-to-market focus`,
      basis: `Target Market: ${form.targetMarket}`,
    })
  }
  if (form?.description && form.description.trim().length > 20) {
    items.push({
      text: 'A detailed project description suggests the concept is well thought through',
      basis: 'Project Description provided',
    })
  }
  if (items.length === 0) {
    items.push({
      text: 'No strong internal advantages identified from the current submission - consider adding more detail.',
      basis: 'Based on current form inputs',
    })
  }
  return items
}

function buildWeaknesses(form) {
  const items = []
  const budgetCr = parseBudgetToCr(form?.budget)

  if (HIGH_COMPLEXITY_MODELS.includes(form?.businessModel)) {
    items.push({
      text: `${form.businessModel} carries meaningfully higher execution complexity than a single-sided SaaS product`,
      basis: `Business Model: ${form.businessModel}`,
    })
  }
  if (budgetCr != null && budgetCr * 100 < 20) {
    items.push({
      text: `A budget of ${form.budget} is thin - limited room to absorb early missteps or a slow start`,
      basis: `Budget: ${form.budget}`,
    })
  } else if (budgetCr == null) {
    items.push({
      text: 'No budget was specified, making runway and financial planning unclear',
      basis: 'Budget field left empty',
    })
  }
  if (!form?.targetMarket || form.targetMarket.trim().length === 0) {
    items.push({
      text: 'No target market was specified - unclear who the first customers actually are',
      basis: 'Target Market field left empty',
    })
  }
  if (!form?.description || form.description.trim().length <= 20) {
    items.push({
      text: 'The project description is brief - the concept may not yet be fully fleshed out',
      basis: 'Project Description is short or empty',
    })
  }
  if (items.length === 0) {
    items.push({
      text: 'No material internal weaknesses identified from the current submission.',
      basis: 'Based on current form inputs',
    })
  }
  return items
}

function buildOpportunities(market, competitors, form) {
  const items = []

  if (market?.somGrowth != null && market.somGrowth > 3) {
    items.push({
      text: `${form?.industry || 'This industry'}'s obtainable market (SOM) is growing at +${market.somGrowth}% - a genuinely expanding opportunity`,
      basis: `SOM growth: +${market.somGrowth}%`,
    })
  }
  if (market?.samGrowth != null && market.samGrowth > 5) {
    items.push({
      text: `The serviceable market (SAM) is growing at +${market.samGrowth}%, ahead of typical baseline growth`,
      basis: `SAM growth: +${market.samGrowth}%`,
    })
  }
  if (competitors && competitors.length > 0) {
    const top = [...competitors].sort((a, b) => b.share - a.share)[0]
    if (top.share < 25) {
      items.push({
        text: `No single competitor dominates (${top.name} leads with only ${top.share}%) - the market is fragmented enough for a new entrant to gain share`,
        basis: `Top competitor share: ${top.share}%`,
      })
    }
    const fastGrowers = competitors.filter((c) => {
      const g = parseFloat(String(c.growth).replace('%', '').replace('+', ''))
      return g >= 20
    })
    if (fastGrowers.length > 0) {
      items.push({
        text: `Fast-growing players like ${fastGrowers[0].name} (${fastGrowers[0].growth}) show strong buyer appetite exists in this space`,
        basis: `${fastGrowers[0].name} growth: ${fastGrowers[0].growth}`,
      })
    }
  }
  if (items.length === 0) {
    items.push({
      text: 'No standout market opportunities identified from current data for this industry.',
      basis: 'Based on current market/competitor data',
    })
  }
  return items
}

function buildThreats(market, competitors, form) {
  const items = []

  if (market?.somGrowth != null && market.somGrowth < 0) {
    items.push({
      text: `${form?.industry || 'This industry'}'s obtainable market (SOM) is shrinking (${market.somGrowth}%) - a real headwind, not just a slow year`,
      basis: `SOM growth: ${market.somGrowth}%`,
    })
  }
  if (competitors && competitors.length > 0) {
    const top = [...competitors].sort((a, b) => b.share - a.share)[0]
    if (top.share >= 25) {
      items.push({
        text: `${top.name} holds a dominant ${top.share}% share - displacing an entrenched leader is difficult without clear differentiation`,
        basis: `Top competitor share: ${top.share}%`,
      })
    }
  }
  if (form?.industry === 'Fintech' || form?.industry === 'Healthcare') {
    items.push({
      text: `${form.industry} carries significant regulatory/compliance overhead in India that can slow launch timelines`,
      basis: `Industry: ${form.industry}`,
    })
  }
  if (items.length === 0) {
    items.push({
      text: 'No major external threats identified from current market/competitor data.',
      basis: 'Based on current market/competitor data',
    })
  }
  return items
}

export function computeSWOT({ form, market, competitors }) {
  return {
    strengths: buildStrengths(form),
    weaknesses: buildWeaknesses(form),
    opportunities: buildOpportunities(market, competitors, form),
    threats: buildThreats(market, competitors, form),
  }
}